#!/bin/sh
#######################################
# TazBot v1.0
# By Brenton Edgar Scott
# Released under the CC0 License
#######################################
python ./modules/tazbot.py > tazbot.log 2>&1 & 